# Generated by Django 4.1.5 on 2023-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemshop',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
